# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _luban
else:
    import _luban

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _luban.delete_SwigPyIterator

    def value(self) -> "PyObject *":
        return _luban.SwigPyIterator_value(self)

    def incr(self, n: "size_t"=1) -> "swig::SwigPyIterator *":
        return _luban.SwigPyIterator_incr(self, n)

    def decr(self, n: "size_t"=1) -> "swig::SwigPyIterator *":
        return _luban.SwigPyIterator_decr(self, n)

    def distance(self, x: "SwigPyIterator") -> "ptrdiff_t":
        return _luban.SwigPyIterator_distance(self, x)

    def equal(self, x: "SwigPyIterator") -> "bool":
        return _luban.SwigPyIterator_equal(self, x)

    def copy(self) -> "swig::SwigPyIterator *":
        return _luban.SwigPyIterator_copy(self)

    def next(self) -> "PyObject *":
        return _luban.SwigPyIterator_next(self)

    def __next__(self) -> "PyObject *":
        return _luban.SwigPyIterator___next__(self)

    def previous(self) -> "PyObject *":
        return _luban.SwigPyIterator_previous(self)

    def advance(self, n: "ptrdiff_t") -> "swig::SwigPyIterator *":
        return _luban.SwigPyIterator_advance(self, n)

    def __eq__(self, x: "SwigPyIterator") -> "bool":
        return _luban.SwigPyIterator___eq__(self, x)

    def __ne__(self, x: "SwigPyIterator") -> "bool":
        return _luban.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n: "ptrdiff_t") -> "swig::SwigPyIterator &":
        return _luban.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n: "ptrdiff_t") -> "swig::SwigPyIterator &":
        return _luban.SwigPyIterator___isub__(self, n)

    def __add__(self, n: "ptrdiff_t") -> "swig::SwigPyIterator *":
        return _luban.SwigPyIterator___add__(self, n)

    def __sub__(self, *args) -> "ptrdiff_t":
        return _luban.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _luban:
_luban.SwigPyIterator_swigregister(SwigPyIterator)

class PyToolKit(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, config_file: "std::string"):
        _luban.PyToolKit_swiginit(self, _luban.new_PyToolKit(config_file))
    __swig_destroy__ = _luban.delete_PyToolKit

    def process(self, features: "char *") -> "std::vector< int64_t,std::allocator< int64_t > >":
        return _luban.PyToolKit_process(self, features)

    def process_file(self, input_file: "std::string", output_file: "std::string") -> "void":
        return _luban.PyToolKit_process_file(self, input_file, output_file)

# Register PyToolKit in _luban:
_luban.PyToolKit_swigregister(PyToolKit)

class Array(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _luban.Array_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _luban.Array___nonzero__(self)

    def __bool__(self) -> "bool":
        return _luban.Array___bool__(self)

    def __len__(self) -> "std::vector< long long >::size_type":
        return _luban.Array___len__(self)

    def __getslice__(self, i: "std::vector< long long >::difference_type", j: "std::vector< long long >::difference_type") -> "std::vector< long long,std::allocator< long long > > *":
        return _luban.Array___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _luban.Array___setslice__(self, *args)

    def __delslice__(self, i: "std::vector< long long >::difference_type", j: "std::vector< long long >::difference_type") -> "void":
        return _luban.Array___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _luban.Array___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< long long >::value_type const &":
        return _luban.Array___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _luban.Array___setitem__(self, *args)

    def pop(self) -> "std::vector< long long >::value_type":
        return _luban.Array_pop(self)

    def append(self, x: "std::vector< long long >::value_type const &") -> "void":
        return _luban.Array_append(self, x)

    def empty(self) -> "bool":
        return _luban.Array_empty(self)

    def size(self) -> "std::vector< long long >::size_type":
        return _luban.Array_size(self)

    def swap(self, v: "Array") -> "void":
        return _luban.Array_swap(self, v)

    def begin(self) -> "std::vector< long long >::iterator":
        return _luban.Array_begin(self)

    def end(self) -> "std::vector< long long >::iterator":
        return _luban.Array_end(self)

    def rbegin(self) -> "std::vector< long long >::reverse_iterator":
        return _luban.Array_rbegin(self)

    def rend(self) -> "std::vector< long long >::reverse_iterator":
        return _luban.Array_rend(self)

    def clear(self) -> "void":
        return _luban.Array_clear(self)

    def get_allocator(self) -> "std::vector< long long >::allocator_type":
        return _luban.Array_get_allocator(self)

    def pop_back(self) -> "void":
        return _luban.Array_pop_back(self)

    def erase(self, *args) -> "std::vector< long long >::iterator":
        return _luban.Array_erase(self, *args)

    def __init__(self, *args):
        _luban.Array_swiginit(self, _luban.new_Array(*args))

    def push_back(self, x: "std::vector< long long >::value_type const &") -> "void":
        return _luban.Array_push_back(self, x)

    def front(self) -> "std::vector< long long >::value_type const &":
        return _luban.Array_front(self)

    def back(self) -> "std::vector< long long >::value_type const &":
        return _luban.Array_back(self)

    def assign(self, n: "std::vector< long long >::size_type", x: "std::vector< long long >::value_type const &") -> "void":
        return _luban.Array_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _luban.Array_resize(self, *args)

    def insert(self, *args) -> "void":
        return _luban.Array_insert(self, *args)

    def reserve(self, n: "std::vector< long long >::size_type") -> "void":
        return _luban.Array_reserve(self, n)

    def capacity(self) -> "std::vector< long long >::size_type":
        return _luban.Array_capacity(self)
    __swig_destroy__ = _luban.delete_Array

# Register Array in _luban:
_luban.Array_swigregister(Array)



