[[operators]]
func = "date"
func_type = 1
input_type = 0
name = "anonymous_0"
type = 9

[[operators]]
func = "concat"
func_type = 2
input_type = 3
name = "anonymous_1"
type = 9
[[operators.params]]
data = "-"
index = 0
type = 3

[[operators.params]]
data = "anonymous_0"
index = 1
type = 9

[[operators]]
func = "concat"
func_type = 3
input_type = 16
name = "anonymous_2"
type = 9
[[operators.params]]
data = "d_s_countryCode"
index = 0
type = 7

[[operators.params]]
data = "anonymous_1"
index = 1
type = 9

[[operators]]
func = "topks"
func_type = 2
input_type = 2
name = "d_c_date"
type = 8
[[operators.params]]
data = "anonymous_2"
index = 0
type = 9

[[operators.params]]
data = 2
index = 1
type = 1

[[operators]]
func = "_identity"
func_type = 1
input_type = 0
name = "d_s_countryCode"
type = 8
[[operators.params]]
data = "d_s_countryCode"
index = 0
type = 7

[[operators]]
func = "timestamp"
func_type = 1
input_type = 0
name = "anonymous_3"
type = 9

[[operators]]
func = "_div"
func_type = 2
input_type = 2
name = "anonymous_4"
type = 9
[[operators.params]]
data = "anonymous_3"
index = 0
type = 9

[[operators.params]]
data = 1000.0
index = 1
type = 2

[[operators]]
func = "_sub"
func_type = 3
input_type = 16
name = "tim_diff"
type = 8
[[operators.params]]
data = "uc_m_timestamp"
index = 0
type = 7

[[operators.params]]
data = "anonymous_4"
index = 1
type = 9

[[operators]]
func = "_log"
func_type = 2
input_type = 1
name = "anonymous_5"
type = 9
[[operators.params]]
data = "d_r_clickValid"
index = 0
type = 7

[[operators]]
func = "_add"
func_type = 2
input_type = 2
name = "d_r_clickValid_log"
type = 8
[[operators.params]]
data = "anonymous_5"
index = 0
type = 9

[[operators.params]]
data = 1000.0
index = 1
type = 2

[[operators]]
func = "_div"
func_type = 2
input_type = 3
name = "d_r_click_div"
type = 8
[[operators.params]]
data = 100000.0
index = 0
type = 2

[[operators.params]]
data = "d_r_click"
index = 1
type = 7

[[operators]]
func = "_div"
func_type = 2
input_type = 2
name = "d_r_click_rdiv"
type = 8
[[operators.params]]
data = "d_r_click"
index = 0
type = 7

[[operators.params]]
data = 100.0
index = 1
type = 2

[[groups]]
gid = 1
name = "d_c_date"

[[groups]]
gid = 2
name = "d_s_countryCode"

[[groups]]
gid = 3
name = "tim_diff"

[[groups]]
gid = 4
name = "d_r_clickValid_log"

[[groups]]
gid = 4
name = "d_r_click_div"

[[groups]]
gid = 4
name = "d_r_click_rdiv"
